services:
  - type: web
    name: contamination-gauge-api
    env: docker
    dockerfilePath: ./be-fastapi/Dockerfile
    dockerContext: ./be-fastapi
    envVars:
      - key: API_KEYS
        sync: false
    healthCheckPath: /health
    plan: free